/** services/mailer.ts */
export const SMTP_SERVICE_TOKEN = 'SMTP_SERVICE_TOKEN';
export const SMTP_KEY_TOKEN = 'SMTP_KEY_TOKEN';
export const SMTP_SECRET_TOKEN = 'SMTP_SECRET_TOKEN';
export const SMTP_MAIL_FROM_TOKEN = 'SMTP_MAIL_FROM_TOKEN';

/** listeners/user.ts */
export const FRONTEND_VERIFICATION_URL_TOKEN = 'FRONTEND_VERIFICATION_URL_TOKEN';
export const FRONTEND_LOGIN_URL_TOKEN = 'FRONTEND_LOGIN_URL_TOKEN';
